### ISSUE TITLE
SystemUI sometimes crashes when switching video to full screen.

### ISSUE THREAD

**Issue by vladrevers** [Evolution-X-AOSP/frameworks_base#430]
It is difficult to detect a clear pattern, but it happens a couple of times a day.

Happened when using the YouTube application and the Firefox browser.

Device: sunfish
Version Android: 13
Version Evolution-X: 7.9 Kare-kare

<details>
  <summary>Log</summary>

  ```
  Process: com.android.systemui
PID: 2743
UID: 10474
Frozen: false
Flags: 0x20c8be0d
Package: com.android.systemui v33 (13)
Foreground: No
Process-Runtime: 13049770
Subject: MediaHierarchyManager
Build: google/sunfish/sunfish:13/TQ2A.230505.002/9891397:user/release-keys
Dropped-Count: 0

android.util.Log$TerribleFailure: mediaFrame height is too small for child: 176 vs 506
	at android.util.Log.wtf(Log.java:315)
	at android.util.Log.wtf(Log.java:279)
	at com.android.systemui.media.controls.ui.MediaHierarchyManager.updateHostAttachment(MediaHierarchyManager.kt:1070)
	at com.android.systemui.media.controls.ui.MediaHierarchyManager.applyState(MediaHierarchyManager.kt:1020)
	at com.android.systemui.media.controls.ui.MediaHierarchyManager.applyState$default(MediaHierarchyManager.kt:1000)
	at com.android.systemui.media.controls.ui.MediaHierarchyManager.cancelAnimationAndApplyDesiredState(MediaHierarchyManager.kt:995)
	at com.android.systemui.media.controls.ui.MediaHierarchyManager.performTransitionToNewLocation(MediaHierarchyManager.kt:773)
	at com.android.systemui.media.controls.ui.MediaHierarchyManager.updateDesiredLocation(MediaHierarchyManager.kt:688)
	at com.android.systemui.media.controls.ui.MediaHierarchyManager.access$updateDesiredLocation(MediaHierarchyManager.kt:87)
	at com.android.systemui.media.controls.ui.MediaHierarchyManager$register$1.invoke(MediaHierarchyManager.kt:597)
	at com.android.systemui.media.controls.ui.MediaHierarchyManager$register$1.invoke(MediaHierarchyManager.kt:591)
	at com.android.systemui.media.controls.ui.MediaHost.updateViewVisibility(MediaHost.kt:209)
	at com.android.systemui.media.controls.ui.MediaHost$listener$1.onMediaDataLoaded(MediaHost.kt:92)
	at com.android.systemui.media.controls.pipeline.MediaDataManager$Listener$DefaultImpls.onMediaDataLoaded$default(MediaDataManager.kt:1376)
	at com.android.systemui.media.controls.pipeline.MediaDataFilter.onMediaDataLoaded(MediaDataFilter.kt:116)
	at com.android.systemui.media.controls.pipeline.MediaDataManager$Listener$DefaultImpls.onMediaDataLoaded$default(MediaDataManager.kt:1376)
	at com.android.systemui.media.controls.pipeline.MediaDataCombineLatest.update(MediaDataCombineLatest.kt:91)
	at com.android.systemui.media.controls.pipeline.MediaDataCombineLatest.onMediaDataLoaded(MediaDataCombineLatest.kt:44)
	at com.android.systemui.media.controls.pipeline.MediaDataManager$Listener$DefaultImpls.onMediaDataLoaded$default(MediaDataManager.kt:1376)
	at com.android.systemui.media.controls.pipeline.MediaSessionBasedFilter$dispatchMediaDataLoaded$1.run(MediaSessionBasedFilter.kt:173)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7926)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
  ```

</details>

**Comment by joeyhuab** [comment]
No updates. Check on QPR3 once again. Until then, closed.
